#!/usr/bin/env python3
"""
Builds the turn-0 data/campaign_state.json from: the fixed 4 Uran missions
already generated by make.py (with their mission_meta.json sidecars), the
19 Nov 1942 historical front-line snapshot closest to the campaign's start
date, and a two-pilot roster per Arin's answer ("two now, room to grow").

Run once, by hand, to create the file. campaign_engine.py never calls this
— only resolve_turn() writes to campaign_state.json after this point.
"""
import json
import os

from build import af_pos, OUT
from campaign_engine import load_frontline_snapshot, save_state, STATE_PATH
from briefings import briefing_for_mission

SECTORS = {
    "rynok_crossing":   "Rynok",
    "marinovka_road":   "Marinovka",
    "gumrak":           "Gumrak",
    "pitomnik_airlift": "Pitomnik",
}

MISSION_SECTOR = {
    "01_Frost_and_Smoke":        ("rynok_crossing",   "1942-11-19"),
    "02_Hammer_at_Marinovka":    ("marinovka_road",   "1942-11-20"),
    "03_Sturmoviks":             ("gumrak",           "1942-11-21"),
    "04_The_Airlift":            ("pitomnik_airlift", "1942-11-23"),
}


def build_seed():
    front = load_frontline_snapshot("1942-11-23")

    sectors = {}
    for key, airfield_name in SECTORS.items():
        x, z, _y = af_pos(airfield_name)
        sectors[key] = {"pos": [x, z], "pressure": 0, "history": []}

    missions = []
    for mission_id, (sector, date) in MISSION_SECTOR.items():
        meta_path = os.path.join(OUT, mission_id + ".mission_meta.json")
        meta = json.load(open(meta_path, "r", encoding="utf-8"))
        missions.append({
            "turn": 0,
            "id": mission_id,
            "sector": sector,
            "date": date,
            "coalition": meta["coalition"],
            "success_obj_id": meta["success_obj_id"],
            "failure_obj_id": meta["failure_obj_id"],
            "status": "pending",
            "result": None,
            "log_sets_applied": [],
            "briefing": briefing_for_mission(OUT, mission_id),
        })

    state = {
        "meta": {"name": "Uran", "version": 1, "created": "2026-08-19"},
        "theaters": {
            "stalingrad": {
                "map_key": "stalingrad-winter",
                "display_name": "Stalingrad",
                "active": True,
                "frontline_dates": [
                    "1942-03-01", "1942-08-01", "1942-09-06", "1942-10-11",
                    "1942-11-23", "1942-12-23", "1943-01-20",
                ],
            }
        },
        "campaign": {
            "turn": 0,
            "date": "1942-11-19",
            "theater": "stalingrad",
            "status": "active",
        },
        "front": {"as_of": "1942-11-23", "coalitions": front},
        "sectors": sectors,
        "pilots": {
            "sloan": {
                "display_name": "Sloan",
                "side": "VVS",
                "status": "active",
                "login_uuids": [],
                "callsign_names_seen": ["CANARY_Sloan"],
                "kills": 0, "deaths": 0, "times_downed": 0, "missions_flown": 0,
                "sorties": [],
            },
            "olorin": {
                "display_name": "Olorin",
                "side": "VVS",
                "status": "active",
                "login_uuids": [],
                "callsign_names_seen": ["CANARY_Olorin"],
                "kills": 0, "deaths": 0, "times_downed": 0, "missions_flown": 0,
                "sorties": [],
            },
        },
        "missions": missions,
        "story": [
            {"turn": 0, "date": "1942-11-19", "title": "Uran",
             "text": ("Before dawn on 19 November 1942, Soviet artillery opened "
                      "along the Don front north-west of Stalingrad. Operation "
                      "Uran had begun: the counteroffensive meant to encircle "
                      "the German Sixth Army in the city it could not take. "
                      "27th Fighter Air Regiment, based at Pichuga on the east "
                      "bank of the Volga, flew top cover and interdiction over "
                      "the crossings and roads that would decide whether the "
                      "pincers closed. What follows is their war.")},
        ],
    }
    return state


if __name__ == "__main__":
    state = build_seed()
    save_state(state)
    print(f"wrote {STATE_PATH}")
    print(f"{len(state['sectors'])} sectors, {len(state['missions'])} missions, "
          f"{len(state['pilots'])} pilots")
